galaxy_info:
  author: leshevi
  description: mysql role
  company: leshevi Ltd
  license: MIT
  min_ansible_version: '2.12'
  platforms:
    - name: Debian
      versions:
        - bullseye
  galaxy_tags: []
dependencies: []
